@ECHO OFF
set TARGET_PLATFORM=%~1
if "%TARGET_PLATFORM%x"=="x" set TARGET_PLATFORM=%PROCESSOR_ARCHITECTURE%
if "%TARGET_PLATFORM%x"=="x" set TARGET_PLATFORM=x86
if not "%TARGET_PLATFORM%"=="x86" if not "%TARGET_PLATFORM%"=="x64" ((set TARGET_PLATFORM=x86) && (goto :EOF))
if "%TARGET_PLATFORM%"=="x86" goto :EOF
if "%TARGET_PLATFORM%"=="x64" (
	if "%PROCESSOR_ARCHITECTURE%"=="x86" if not defined PROCESSOR_ARCHITEW6432 ((set TARGET_PLATFORM=x86_amd64) && (goto :EOF))
	if "%PROCESSOR_ARCHITECTURE%"=="IA64" ((set TARGET_PLATFORM=ia64) && (goto :EOF))
	if "%PROCESSOR_ARCHITEW6432%"=="IA64" ((set TARGET_PLATFORM=ia64) && (goto :EOF))
	set TARGET_PLATFORM=amd64
	goto :EOF
)
if "%TARGET_PLATFORM%"=="AMD64" ((set TARGET_PLATFORM=amd64) && (goto :EOF))
if "%TARGET_PLATFORM%"=="IA64" ((set TARGET_PLATFORM=ia64) && (goto :EOF))